# site settings
title: "JKU GAMES 2025W"
subtitle: "JKU Linz, Uni-Center, 05. - 07.12."
email: "games@oeh.jku.at"
# description: "05.12. 16:00 - 07.12.2025 06:00 <br>> We are currently planning this event, not all information is up-to-date!"
description: "05.12. 16:00 - 07.12.2025 06:00 <br>> 38 hours non-stop entertainment, for free!"
baseurl: "" 
url: "https://games.oeh.jku.at/"
author: JKU Games Team
street_address: "JKU Linz, Uni-Center<br>Altenbergerstraße 69"
city: Linz
state: AT
zip_code: 4040
country: Österreich
phone: 

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 8

# social settings
500px_url: 
facebook_url: "https://facebook.com/jkugames"
github_url: 
gitlab_url: 
googleplus_url: 
instagram_url: "https://instagram.com/oehtnf"
linkedin_url: 
pinterest_url:
slack_url:
twitter_url: 
discord_url: "https://discord.gg/46Hg8v57s9"

# build settings
markdown: kramdown

sass:
  style: compressed
